class MenuItem {
  final String name;
  final String location;
  final double price;
  final String description;
  final double weight;
  final List<String> ingredients;
  final int calories;
  final int preparationTime; // in minutes
  final bool isAvailable;
  final String restaurantName;
  final List<String> availableSizes; // Added available sizes
  final Map<String, double> sizePrices; // Added size prices
  final String category;
  bool? isFavorite;

  MenuItem({
    required this.name,
    required this.location,
    required this.price,
    required this.description,
    required this.weight,
    required this.ingredients,
    required this.calories,
    required this.preparationTime,
    required this.isAvailable,
    required this.restaurantName,
    required this.availableSizes, // Added available sizes
    required this.sizePrices, // Added size prices
    this.isFavorite = false,
    required this.category
  });

  static List<String> getCategories(List<MenuItem> menu) {
  return menu.map((item) => item.category).toSet().toList();
  }
}

List<MenuItem> menu = [
  MenuItem(
    name: "Original Beef Burger",
    location: "assets/images/item (1).png",
    price: 2.99,
    description: "Juicy beef burger with original flavor, made from premium ground beef, seasoned with a blend of spices and grilled to perfection...",
    weight: 250.0,
    ingredients: ["Beef patty", "Lettuce", "Tomato", "Onion", "Pickles", "Burger bun"],
    calories: 550,
    preparationTime: 15,
    isAvailable: true,
    restaurantName: "Fake Burger Joint",
    availableSizes: ["Small", "Medium", "Large"],
    sizePrices: {
      "Small": 2.99,
      "Medium": 3.99,
      "Large": 4.99,
    },
    category: "Burgers",
  ),
  MenuItem(
    name: "Beef Burger & Fries",
    location: "assets/images/item (2).png",
    price: 3.49,
    description: "Classic beef burger served with crispy fries...",
    weight: 300.0,
    ingredients: ["Beef patty", "Lettuce", "Tomato", "Onion", "Pickles", "Burger bun", "Fries"],
    calories: 800,
    preparationTime: 20,
    isAvailable: true,
    restaurantName: "Fake Burger Joint",
    availableSizes: ["Medium", "Large"],
    sizePrices: {
      "Medium": 3.49,
      "Large": 4.49,
    },
    category: "Burgers",
  ),
  MenuItem(
    name: "Chicken Burger\nExtra Ranch",
    location: "assets/images/item (3).png",
    price: 3.99,
    description: "Spicy chicken burger with extra ranch dressing...",
    weight: 270.0,
    ingredients: ["Chicken patty", "Lettuce", "Tomato", "Ranch dressing", "Burger bun"],
    calories: 600,
    preparationTime: 18,
    isAvailable: true,
    restaurantName: "Chicken Palace",
    availableSizes: ["Small", "Medium"],
    sizePrices: {
      "Small": 3.99,
      "Medium": 4.99,
    },
    category: "Burgers",
  ),
  MenuItem(
    name: "Chicken Roll",
    location: "assets/images/item (4).png",
    price: 2.99,
    description: "Delicious chicken roll with fresh veggies...",
    weight: 200.0,
    ingredients: ["Chicken strips", "Lettuce", "Tomato", "Tortilla wrap"],
    calories: 450,
    preparationTime: 12,
    isAvailable: true,
    restaurantName: "Chicken Palace",
    availableSizes: ["Regular"],
    sizePrices: {
      "Regular": 2.99,
    },
    category: "Rolls",
  ),
  MenuItem(
    name: "Zo Beef Burger",
    location: "assets/images/item (5).png",
    price: 3.99,
    description: "Special beef burger with Zo's secret sauce...",
    weight: 280.0,
    ingredients: ["Beef patty", "Lettuce", "Tomato", "Onion", "Pickles", "Secret sauce", "Burger bun"],
    calories: 570,
    preparationTime: 15,
    isAvailable: true,
    restaurantName: "Zo's Grill",
    availableSizes: ["Small", "Medium", "Large"],
    sizePrices: {
      "Small": 3.99,
      "Medium": 4.99,
      "Large": 5.99,
    },
    category: "Burgers",
  ),
  MenuItem(
    name: "Super Beef Burger",
    location: "assets/images/item (6).png",
    price: 4.99,
    description: "Large beef burger for the super hungry...",
    weight: 350.0,
    ingredients: ["Beef patty", "Lettuce", "Tomato", "Onion", "Pickles", "Burger bun"],
    calories: 900,
    preparationTime: 22,
    isAvailable: true,
    restaurantName: "Fake Burger Joint",
    availableSizes: ["Large"],
    sizePrices: {
      "Large": 4.99,
    },
    category: "Burgers",
  ),
  MenuItem(
    name: "Veggie Delight",
    location: "https://www.subway.com.hk/wp-content/uploads/2017/07/vd-450x450.png",
    price: 3.49,
    description: "A delightful burger with fresh veggies...",
    weight: 240.0,
    ingredients: ["Veggie patty", "Lettuce", "Tomato", "Onion", "Cucumber", "Burger bun"],
    calories: 400,
    preparationTime: 12,
    isAvailable: true,
    restaurantName: "Veggie Haven",
    availableSizes: ["Small", "Medium"],
    sizePrices: {
      "Small": 3.49,
      "Medium": 4.49,
    },
    category: "Sandwiches",
  ),
  MenuItem(
    name: "Spicy Chicken Burger",
    location: "https://heroburgers.com/wp-content/uploads/JalapenoSpicyCrispyChicken-1-min.png",
    price: 4.49,
    description: "A burger with spicy grilled chicken...",
    weight: 250.0,
    ingredients: ["Chicken patty", "Lettuce", "Tomato", "Jalapenos", "Burger bun"],
    calories: 620,
    preparationTime: 15,
    isAvailable: true,
    restaurantName: "Chicken Palace",
    availableSizes: ["Medium"],
    sizePrices: {
      "Medium": 4.49,
    },
    category: "Burgers",
  ),
  MenuItem(
    name: "Fish Fillet Burger",
    location: "https://burgerking.com.my/upload/image/Product/39/Fish%20N%20Crisp%20Ala%20Carte.png",
    price: 3.99,
    description: "Crispy fish fillet in a soft bun...",
    weight: 230.0,
    ingredients: ["Fish fillet", "Lettuce", "Tartar sauce", "Burger bun"],
    calories: 500,
    preparationTime: 14,
    isAvailable: true,
    restaurantName: "Seafood Shack",
    availableSizes: ["Small", "Medium"],
    sizePrices: {
      "Small": 3.99,
      "Medium": 4.99,
    },
    category: "Burgers",
  ),
  MenuItem(
    name: "Double Cheese Burger",
    location: "https://burgerkingks.com/wp-content/uploads/2020/08/double-cheeseburger-ss-NEW.png",
    price: 5.49,
    description: "Beef burger with double cheese...",
    weight: 320.0,
    ingredients: ["Beef patty", "Cheddar cheese", "Lettuce", "Tomato", "Onion", "Burger bun"],
    calories: 750,
    preparationTime: 18,
    isAvailable: true,
    restaurantName: "Fake Burger Joint",
    availableSizes: ["Medium", "Large"],
    sizePrices: {
      "Medium": 5.49,
      "Large": 6.49,
    },
    category: "Burgers",
  ),
  MenuItem(
    name: "Grilled Chicken Wrap",
    location: "https://cajjhieqsa.cloudimg.io/https://f004.backblazeb2.com/file/pepe-piri-piri/misc/994fb43cc2820dfe4472a1ef5b8ccfdc.png?w=500&org_if_sml=1",
    price: 3.99,
    description: "Grilled chicken wrap with veggies...",
    weight: 220.0,
    ingredients: ["Grilled chicken", "Lettuce", "Tomato", "Tortilla wrap"],
    calories: 420,
    preparationTime: 12,
    isAvailable: true,
    restaurantName: "Chicken Palace",
    availableSizes: ["Regular"],
    sizePrices: {
      "Regular": 3.99,
    },
    category: "Wraps",
  ),
  MenuItem(
    name: "BBQ Beef Burger",
    location: "https://www.burgerandsauce.com/wp-content/uploads/2021/02/burger-and-sauce-beef-burger-3000px2-1-1024x1024.png",
    price: 4.99,
    description: "Beef burger with BBQ sauce...",
    weight: 310.0,
    ingredients: ["Beef patty", "BBQ sauce", "Lettuce", "Tomato", "Burger bun"],
    calories: 680,
    preparationTime: 16,
    isAvailable: true,
    restaurantName: "Fake Burger Joint",
    availableSizes: ["Small", "Medium"],
    sizePrices: {
      "Small": 4.99,
      "Medium": 5.99,
    },
    category: "Burgers",
  ),
  MenuItem(
    name: "Classic Hot Dog",
    location: "https://bk-latam-prod.s3.amazonaws.com/sites/burgerking.bs/files/Classic_Detail_v2-min.png",
    price: 2.99,
    description: "Classic hot dog with mustard and ketchup...",
    weight: 200.0,
    ingredients: ["Hot dog sausage", "Mustard", "Ketchup", "Hot dog bun"],
    calories: 300,
    preparationTime: 10,
    isAvailable: true,
    restaurantName: "Hot Dog Haven",
    availableSizes: ["Regular"],
    sizePrices: {
      "Regular": 2.99,
    },
    category: "Sandwiches",
  ),
  MenuItem(
    name: "Cheese Steak Sandwich",
    location: "https://static.vecteezy.com/system/resources/previews/027/143/542/original/philly-cheesesteak-sandwich-isolated-on-transparent-background-free-png.png",
    price: 5.99,
    description: "Cheese steak sandwich with peppers...",
    weight: 350.0,
    ingredients: ["Steak", "Cheese", "Peppers", "Onions", "Hoagie roll"],
    calories: 900,
    preparationTime: 20,
    isAvailable: true,
    restaurantName: "Steak House",
    availableSizes: ["Large"],
    sizePrices: {
      "Large": 5.99,
    },
    category: "Sandwiches",
  ),
  MenuItem(
    name: "Bacon Cheeseburger",
    location: "https://bk-latam-prod.s3.amazonaws.com/sites/burgerking.bs/files/New_%20BaconCheeseburger_detail.png",
    price: 5.49,
    description: "Beef burger with bacon and cheese...",
    weight: 340.0,
    ingredients: ["Beef patty", "Bacon", "Cheddar cheese", "Lettuce", "Tomato", "Burger bun"],
    calories: 800,
    preparationTime: 18,
    isAvailable: true,
    restaurantName: "Fake Burger Joint",
    availableSizes: ["Medium", "Large"],
    sizePrices: {
      "Medium": 5.49,
      "Large": 6.49,
    },
    category: "Burgers",
  ),
  MenuItem(
    name: "Mushroom Swiss Burger",
    location: "https://hrdprodcmsimages-d4d2dhb9fvh9ftde.a03.azurefd.net/hrdprodcmsimages/hrd/uae/imagestemp/130004.png",
    price: 4.99,
    description: "Beef burger with mushrooms and Swiss cheese...",
    weight: 320.0,
    ingredients: ["Beef patty", "Mushrooms", "Swiss cheese", "Lettuce", "Tomato", "Burger bun"],
    calories: 700,
    preparationTime: 17,
    isAvailable: true,
    restaurantName: "Fake Burger Joint",
    availableSizes: ["Medium"],
    sizePrices: {
      "Medium": 4.99,
    },
    category: "Burgers",
  ),
];
